{
  'annotations_file': 'C:\Users\skrzy\Music\sample_music\metadata.csv',
  'music_dir': 'C:\Users\skrzy\Music\sample_music',
  'music_parts': [ 'Chorus', 'Verse' ],
  'temp_dir': 'C:\Users\skrzy\Music\sample_music',
  'models_path': 'C:\Users\skrzy\Music\sample_music',
  'reference_music': 'Calla - Swagger',
  'batch_size': 2,
  'norm': "cosine",
  'how_many': 5,
  'num_epochs': 2,
  'lr': 0.002,
  'triplet_loss_margin': 1.0,
  'output_dir': 'C:\Users\skrzy\Music\results'
}