{
  'annotations_file': 'C:\Users\skrzy\Music\e2e_test\metadata.csv',
  'val_annotations_file': 'C:\Users\skrzy\Music\e2e_test\val_metadata.csv',
  'music_dir': 'C:\Users\skrzy\Music\e2e_test',
  'music_parts': [ 'Chorus', 'Verse' ],
  'temp_dir': 'C:\Users\skrzy\Music\sample_music',
  'models_path': 'C:\Users\skrzy\Music\e2e_test',
  'reference_music': 'Calla - Swagger',
  'batch_size': 16,
  'num_epochs': 30,
  'lr': 0.002,
  'triplet_loss_margin': 1.0,
  'output_dir': 'C:\Users\skrzy\Music\e2e_test\results'
}